init
Devops-2022-Group-R/itu-minitwit pull request #135
Opened 2022-05-24 07:56 UTC by ThomasITU

2022-05-24 09:43 UTC, avborup approved these changes

2022-05-24 09:43 UTC, avborup commented on report/sections/system-perspective/system-dependencies.tex
> +        \textbf{Code analysis} & \textbf{SonarCloud, lint, cyclomatic} & reduce code smell \\
```suggestion
        \textbf{Version control} & \textbf{Git, GitHub} & ?? \\
        \textbf{Pipeline CI/CD} & \textbf{CircleCi} & ?? \\
        \textbf{Containerization} & \textbf{Docker and DockerHub} & For development and deployment to DockerHub \\
        \textbf{Database} & \textbf{SQL Server, SQLite} & To store data \\
        \textbf{Service Provider} & \textbf{Azure, own server} & Hosting our app \\
        \textbf{Infrastructure} & \textbf{Terraform} & IaC, to easily swap host, automating tasks  \\
        \textbf{Service management} & \textbf{Kubernetes} & orchestra containers, scaling up / down  \\
        \textbf{Logging} & \textbf{Elasticsearch, Fluentd and Kibana} & Gather, filter, and search through a centralized log  \\
        \textbf{Monitoring} & \textbf{Grafana and Prometheus} & Alerts, performance, response time, represented visualy \\
        \textbf{Security} & \textbf{Snyk} & Notify about Security issues and updates to dependencies \\
        \textbf{Languages and frameworks} & \textbf{Golang, gin-gonic, Gorm, testify, JavaScript, VueJS} \\
        \textbf{Documentation?(report)} & \textbf{LaTeX, Markdown} & ? \\
        \textbf{Code analysis} & \textbf{SonarCloud, lint, cyclomatic} & reduce code smell \\
```

2022-05-24 09:50 UTC, albe2669 requested changes

2022-05-25 09:01 UTC, albe2669 submitted a review, later dismissed

2022-05-25 09:49 UTC, albe2669 submitted a review, later dismissed

2022-05-25 10:05 UTC, avborup approved these changes

2022-05-25 10:05 UTC, merged